# Generated by Django 5.1.3 on 2024-12-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_remove_gasto_categoria_gasto_parcela'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='uploads/')),
                ('upload_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
