# Generated by Django 5.1.3 on 2024-12-03 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_alter_arquivogasto_arquivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadArquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='assets/csv/')),
                ('upload_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ArquivoGasto',
        ),
        migrations.DeleteModel(
            name='Gasto',
        ),
    ]
