# Generated by Django 5.1.3 on 2024-12-04 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_uploadarquivo_delete_arquivogasto_delete_gasto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('parcela', models.CharField(blank=True, max_length=20, null=True)),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='GastoPessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.gasto')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.pessoa')),
            ],
        ),
        migrations.AddField(
            model_name='gasto',
            name='pessoas',
            field=models.ManyToManyField(through='expenses.GastoPessoa', to='expenses.pessoa'),
        ),
    ]
