# Generated by Django 5.1.3 on 2024-12-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_uploadedfile_remove_gasto_pessoas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to='arquivos/'),
        ),
    ]
