# Generated by Django 5.1.3 on 2024-12-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0012_gasto_pessoa_delete_compra_delete_uploadedfile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('parcela', models.CharField(blank=True, max_length=20, null=True)),
                ('valor', models.FloatField()),
                ('data', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Gasto',
        ),
    ]
