# Generated by Django 5.1.3 on 2024-12-06 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0013_processeddata_delete_gasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='processeddata',
            name='pessoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos', to='expenses.pessoa'),
        ),
    ]
