# Generated by Django 5.1.3 on 2024-12-10 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0014_processeddata_pessoa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processeddata',
            name='pessoa',
        ),
    ]
