# Generated by Django 5.1.3 on 2024-12-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0017_alter_processeddata_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='processeddata',
            name='valor_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
