# Generated by Django 5.1.3 on 2024-12-18 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0019_alter_processeddata_pessoa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processeddata',
            name='valor_total',
        ),
    ]
