# Generated by Django 5.1.3 on 2024-12-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0021_rename_processeddata_gasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='valor_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
