# Generated by Django 5.1.3 on 2024-12-26 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0022_gasto_valor_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gasto',
            old_name='pessoa',
            new_name='pessoas',
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='valor_total',
        ),
        migrations.AddField(
            model_name='gasto',
            name='is_divided',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gasto',
            name='valor_original',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='GastoPessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_dividido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.gasto')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.pessoa')),
            ],
            options={
                'unique_together': {('gasto', 'pessoa')},
            },
        ),
    ]
