# Generated by Django 5.1.3 on 2024-12-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0023_rename_pessoa_gasto_pessoas_remove_gasto_valor_total_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gasto',
            old_name='pessoas',
            new_name='pessoa',
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='is_divided',
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='valor_original',
        ),
        migrations.AddField(
            model_name='gasto',
            name='valor_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='valor',
            field=models.FloatField(),
        ),
        migrations.DeleteModel(
            name='GastoPessoa',
        ),
    ]
