# Generated by Django 5.1.3 on 2025-01-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0024_rename_pessoas_gasto_pessoa_remove_gasto_is_divided_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasto',
            name='pessoa',
        ),
        migrations.AddField(
            model_name='gasto',
            name='pessoa',
            field=models.ManyToManyField(blank=True, to='expenses.pessoa'),
        ),
    ]
