# Generated by Django 5.1.3 on 2025-01-17 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0026_gasto_is_divided'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasto',
            name='is_divided',
        ),
    ]
