# Generated by Django 5.1.3 on 2025-01-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0027_remove_gasto_is_divided'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='is_divided',
            field=models.BooleanField(default=False),
        ),
    ]
